### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by MuteScream** [LocusAzzurro/icaruswings_mod#26]
游戏环境：1.18.2-Forge_40.1.0-OptiFine_H7
mod版本：0.3.0
问题描述：收集遗物做成的神话系羽翼在附魔经验修补并消耗耐久后，拾取经验球的瞬间游戏崩溃。
错误报告：[crash-2022-05-15_03.19.48-server.txt](https://github.com/LocusAzzurro/icaruswings_mod/files/8693750/crash-2022-05-15_03.19.48-server.txt)

**Comment by LocusAzzurro** [comment]
开发环境未能复现，尝试了神话线羽翼和未来线羽翼，尝试一下在仅安装本Mod的情况下是否会出现同样的问题？

**Comment by MuteScream** [comment]
会出现同样的问题。
测试流程：使用enchant指令给“[反逆可变翼](https://www.mcmod.cn/item/479705.html)”附魔经验修补，飞行消耗耐久后使用附魔之瓶，接触到掉落的经验球时游戏崩溃。
[crash-2022-05-15_16.53.50-server.txt](https://github.com/LocusAzzurro/icaruswings_mod/files/8694582/crash-2022-05-15_16.53.50-server.txt)
