### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by huozhijueyi** [LocusAzzurro/icaruswings_mod#6]
金色羽毛扎与闪烁的精炼蜂蜜蜡做的羽翼仍为彩色羽翼
鞘翅制作的魔法之翼和芙兰朵露的魔法之翼无法在末地使用，在下界使用会着火
将蜂蜜放入陶制蜜酒罐中无法获取蜜酒
（遗物和灵风精髓的获取方式能不能来点提示doge，还有蓝宝石是做什么的）

**Comment by LocusAzzurro** [comment]
蓝黄玉宝石、蓝宝石、群青宝石是交易货币，不计划添加直接合成的途径。

**Comment by LocusAzzurro** [comment]
关于蜜酒罐，机制是需要发酵三个游戏日（等液体从橙色转为金黄）才能获取，如果存在问题可提另一个issue
获取相关documentation需求稍候另行创建一个issue记录

**Comment by LocusAzzurro** [comment]
Magic Wings issue still presists, see #17
